interface:
  stage: build
  script:
    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/iochq/hybridd/common/-/jobs/104274327/artifacts/download\""
    - "./scripts/npm/build.sh"
    - "webpack-cli --help"
  artifacts:
    paths:
    - ./dist/
