interface:
  stage: deploy
  script:
    - curl --location --header JOB-TOKEN: $CI_JOB_TOKEN https://gitlab.com/iochq/hybridd/common/-/jobs/104274327/artifacts/download
    - ./scripts/npm/build.sh
    - webpack --help
  artifacts:
    paths:
    - ./dist/
