image: node:8.12.0-stretch

#common:
#  stage: build
#  script: 
   # trigger pipeline common
   #- "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/trigger/pipeline"

interface:
  stage: build
  script:
    - init
    # install unzip
    - apt-get update
    - apt-get install unzip
    
    # trigger pipeline common
    # "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/trigger/pipeline"
    
    # download [common] artifact
    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/jobs/artifacts/master/download?job=common\" -o artifacts-common.zip"
    
    # remove link to common and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
    - rm -rf  common || true
    - unzip -o artifacts-common.zip -d common
    
    # remove the zip-file (|| true --> on error, no problem)
    - rm -rf  artifacts-common.zip || true
    
    # remove symbolic link to node
    - rm -rf  node || true
    # don't download git clone https://github.com/internetofcoins/nodejs-v8-lts.git, refer to docker pre installed nodejs as defined in the first line of this file
    - ln -s "$(which nodejs)" node
    
    - ./scripts/npm/compile.sh debug
    # clean up and prepare the artifacts (instead of having a dist) 
    # remove everything except () is extglob syntax, which should be enabled first
    - shopt -s extglob
    - rm -rf !(dist) || true
    - mv ./dist/* ./
    - rm -rf ./dist || true
    
    # remove .git directory and .* files
    - rm -rf ./.git* || true
  artifacts:
    paths:
    - ./*

#interface-debug:
  #stage: build
  #script:
    #- init
    #- ./scripts/npm/compile.sh debug
    #- dist
  #artifacts:
    #paths:
#    - ./*
    
# ---------------------------------------------------------------------------

.auto_devops: &auto_devops |
# Auto DevOps variables and functions
 
  function init() {
    echo "init"
  }

before_script:
  - *auto_devops
