image: node:8.12.0-stretch

interface:
  stage: build
  script:
    - init
 
    # trigger pipeline common
    # "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/trigger/pipeline"
    
    # download [common] artifact
    #- "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/jobs/artifacts/master/download?job=common\" -o artifacts-common.zip"
    
    
    # compile in debug
    - ./scripts/npm/compile.sh
    
    - shopt -s extglob
    - rm -rf !(dist) || true
    - dist
  artifacts:
    paths:
    - ./*

interface-debug:
  stage: build
  script:
    - init
    
    # trigger pipeline common
    # "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/trigger/pipeline"
    
    # download [common] artifact
    #- "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/jobs/artifacts/master/download?job=common\" -o artifacts-common.zip"
    
    # compile in debug
    - ./scripts/npm/compile.sh debug
    
    - shopt -s extglob
    - rm -rf !(dist) || true
    - dist
  artifacts:
    paths:
    - ./*
    

# ---------------------------------------------------------------------------

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions

  function init() {
    apt-get update
    apt-get install unzip
    curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/jobs/artifacts/master/download?job=common" -o artifacts-common.zip
    
    # remove link to common and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
    rm -rf  common || true
    unzip -o artifacts-common.zip -d common
    
    # remove the zip-file (|| true --> on error, no problem)
    rm -rf  artifacts-common.zip || true
    
    # remove symbolic link to node
    rm -rf  node || true
    # don't download git clone https://github.com/internetofcoins/nodejs-v8-lts.git, refer to docker pre installed nodejs as defined in the first line of this file
    ln -s "$(which nodejs)" node
  }
  
  function dist() {
    # clean up and prepare the artifacts (instead of having a dist)
    mv ./dist/* ./
    rm -rf ./dist || true
    
    # remove .git directory and .* files
    rm -rf ./.git* || true
  }

before_script:
  - *auto_devops