interface:
  stage: build
  script:
    # install unzip
    - apt-get update
    - apt-get install unzip
    
    # trigger pipeline common
    # - "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/trigger/pipeline"
    
    # download [common] artifact
    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/iochq%2Fhybridd%2Fcommon/jobs/artifacts/master/download?job=common\" -o artifacts-common.zip"
    
    # create directory for [common] and unzip the downloaded artifact to that
    - mkdir -p common
    - unzip -o artifacts-common.zip -d common
    
    # remove the zip-file (|| true --> on error, no problem)
    - rm -rf  artifacts-common.zip || true
    
    # run the build-script of the interface
    - ./scripts/npm/build.sh
    
    #- ./node_modules/webpack/bin/webpack.js --help
  artifacts:
    paths:
    - ./dist/